# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0002_dataupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='value',
            field=models.BooleanField(default=False),
        ),
    ]
